language: go

go:
  - tip

before_install:
  - echo 'deb http://repo.reverbrain.com/precise current/amd64/' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install elliptics-dev elliptics-client elliptics libboost-system-dev --force-yes
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - cd fixtures && sudo ./start.sh && cd - && sleep 10
  - export FULL_TEST_REMOTES="localhost:1025:2" && export FULL_TEST_GROUPS="2"

script:
  - go test -v -coverprofile=coverage.out github.com/noxiouz/elliptics-go/elliptics
  - go tool cover -func=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken d6Fnx2wcqx7Bk302wLSoeYbaDcxn3POKW

branches:
  only:
  - "master"
